#!/usr/bin/env python
# -*- coding: utf-8 -*-
import subprocess
from argparse import ArgumentParser
from glob import glob
from os import path as osp


def main():
    base_dir = osp.dirname(__file__)
    parser = ArgumentParser()
    default_output_dir = osp.join(base_dir, 'site')
    parser.add_argument('-o', '--output-dir',
                        default=default_output_dir)
    args = parser.parse_args()
    out_dir = args.output_dir

    run(['rm', '-fr', out_dir])
    run(['lektor', 'clean', '--yes'])
    run(['lektor', 'build', '-O', out_dir])

    # XXX: 'lektor build' doesn't copy the attachments properly like 'lektor server'
    run(['cp'] + glob(osp.join(out_dir, '*.jpg')) + [osp.join(out_dir, 'zh')])

    run(['cp', osp.join(base_dir, 'assets/_redirects'), out_dir])

def run(command):
    print '+ {}'.format(subprocess.list2cmdline(command))
    subprocess.check_call(command)


if __name__ == '__main__':
    main()
